/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ForeverBusinessRouteImport } from './routes/forever-business'
import { Route as ForeverCityRouteImport } from './routes/forever-city'
import { Route as ForeverHolidaysRouteImport } from './routes/forever-holidays'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as MembershipRouteImport } from './routes/membership'
import { Route as OffersRouteImport } from './routes/offers'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as AuthenticatedMemberRouteRouteImport } from './routes/_authenticated/member/route'
import { Route as AuthenticatedOwnerRouteRouteImport } from './routes/_authenticated/owner/route'
import { Route as AuthenticatedPortalRouteImport } from './routes/_authenticated/portal'
import { Route as ResortsIndexRouteImport } from './routes/resorts.index'
import { Route as AuthenticatedAdminAnalyticsRouteImport } from './routes/_authenticated/admin/analytics'
import { Route as AuthenticatedAdminDashboardRouteImport } from './routes/_authenticated/admin/dashboard'
import { Route as AuthenticatedMemberBookingsRouteImport } from './routes/_authenticated/member/bookings'
import { Route as AuthenticatedMemberDashboardRouteImport } from './routes/_authenticated/member/dashboard'
import { Route as AuthenticatedMemberHolidaysRouteImport } from './routes/_authenticated/member/holidays'
import { Route as AuthenticatedMemberMembershipRouteImport } from './routes/_authenticated/member/membership'
import { Route as AuthenticatedOwnerDashboardRouteImport } from './routes/_authenticated/owner/dashboard'
import { Route as AuthenticatedAdminResortsIndexRouteImport } from './routes/_authenticated/admin/resorts.index'
import { Route as AuthenticatedAdminResortsResortIdRouteImport } from './routes/_authenticated/admin/resorts.$resortId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ForeverBusinessRoute = ForeverBusinessRouteImport.update({
  id: '/forever-business',
  path: '/forever-business',
  getParentRoute: () => rootRouteImport,
} as any)
const ForeverCityRoute = ForeverCityRouteImport.update({
  id: '/forever-city',
  path: '/forever-city',
  getParentRoute: () => rootRouteImport,
} as any)
const ForeverHolidaysRoute = ForeverHolidaysRouteImport.update({
  id: '/forever-holidays',
  path: '/forever-holidays',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const MembershipRoute = MembershipRouteImport.update({
  id: '/membership',
  path: '/membership',
  getParentRoute: () => rootRouteImport,
} as any)
const OffersRoute = OffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMemberRouteRoute =
  AuthenticatedMemberRouteRouteImport.update({
    id: '/member',
    path: '/member',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOwnerRouteRoute = AuthenticatedOwnerRouteRouteImport.update({
  id: '/owner',
  path: '/owner',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPortalRoute = AuthenticatedPortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ResortsIndexRoute = ResortsIndexRouteImport.update({
  id: '/resorts/',
  path: '/resorts/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminAnalyticsRoute =
  AuthenticatedAdminAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminDashboardRoute =
  AuthenticatedAdminDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedMemberBookingsRoute =
  AuthenticatedMemberBookingsRouteImport.update({
    id: '/bookings',
    path: '/bookings',
    getParentRoute: () => AuthenticatedMemberRouteRoute,
  } as any)
const AuthenticatedMemberDashboardRoute =
  AuthenticatedMemberDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedMemberRouteRoute,
  } as any)
const AuthenticatedMemberHolidaysRoute =
  AuthenticatedMemberHolidaysRouteImport.update({
    id: '/holidays',
    path: '/holidays',
    getParentRoute: () => AuthenticatedMemberRouteRoute,
  } as any)
const AuthenticatedMemberMembershipRoute =
  AuthenticatedMemberMembershipRouteImport.update({
    id: '/membership',
    path: '/membership',
    getParentRoute: () => AuthenticatedMemberRouteRoute,
  } as any)
const AuthenticatedOwnerDashboardRoute =
  AuthenticatedOwnerDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedOwnerRouteRoute,
  } as any)
const AuthenticatedAdminResortsIndexRoute =
  AuthenticatedAdminResortsIndexRouteImport.update({
    id: '/resorts/',
    path: '/resorts/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminResortsResortIdRoute =
  AuthenticatedAdminResortsResortIdRouteImport.update({
    id: '/resorts/$resortId',
    path: '/resorts/$resortId',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/forever-business': typeof ForeverBusinessRoute
  '/forever-city': typeof ForeverCityRoute
  '/forever-holidays': typeof ForeverHolidaysRoute
  '/how-it-works': typeof HowItWorksRoute
  '/membership': typeof MembershipRoute
  '/offers': typeof OffersRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/member': typeof AuthenticatedMemberRouteRouteWithChildren
  '/owner': typeof AuthenticatedOwnerRouteRouteWithChildren
  '/portal': typeof AuthenticatedPortalRoute
  '/resorts/': typeof ResortsIndexRoute
  '/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/member/bookings': typeof AuthenticatedMemberBookingsRoute
  '/member/dashboard': typeof AuthenticatedMemberDashboardRoute
  '/member/holidays': typeof AuthenticatedMemberHolidaysRoute
  '/member/membership': typeof AuthenticatedMemberMembershipRoute
  '/owner/dashboard': typeof AuthenticatedOwnerDashboardRoute
  '/admin/resorts/$resortId': typeof AuthenticatedAdminResortsResortIdRoute
  '/admin/resorts/': typeof AuthenticatedAdminResortsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/forever-business': typeof ForeverBusinessRoute
  '/forever-city': typeof ForeverCityRoute
  '/forever-holidays': typeof ForeverHolidaysRoute
  '/how-it-works': typeof HowItWorksRoute
  '/membership': typeof MembershipRoute
  '/offers': typeof OffersRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/member': typeof AuthenticatedMemberRouteRouteWithChildren
  '/owner': typeof AuthenticatedOwnerRouteRouteWithChildren
  '/portal': typeof AuthenticatedPortalRoute
  '/resorts': typeof ResortsIndexRoute
  '/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/member/bookings': typeof AuthenticatedMemberBookingsRoute
  '/member/dashboard': typeof AuthenticatedMemberDashboardRoute
  '/member/holidays': typeof AuthenticatedMemberHolidaysRoute
  '/member/membership': typeof AuthenticatedMemberMembershipRoute
  '/owner/dashboard': typeof AuthenticatedOwnerDashboardRoute
  '/admin/resorts/$resortId': typeof AuthenticatedAdminResortsResortIdRoute
  '/admin/resorts': typeof AuthenticatedAdminResortsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/forever-business': typeof ForeverBusinessRoute
  '/forever-city': typeof ForeverCityRoute
  '/forever-holidays': typeof ForeverHolidaysRoute
  '/how-it-works': typeof HowItWorksRoute
  '/membership': typeof MembershipRoute
  '/offers': typeof OffersRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/member': typeof AuthenticatedMemberRouteRouteWithChildren
  '/_authenticated/owner': typeof AuthenticatedOwnerRouteRouteWithChildren
  '/_authenticated/portal': typeof AuthenticatedPortalRoute
  '/resorts/': typeof ResortsIndexRoute
  '/_authenticated/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/_authenticated/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/_authenticated/member/bookings': typeof AuthenticatedMemberBookingsRoute
  '/_authenticated/member/dashboard': typeof AuthenticatedMemberDashboardRoute
  '/_authenticated/member/holidays': typeof AuthenticatedMemberHolidaysRoute
  '/_authenticated/member/membership': typeof AuthenticatedMemberMembershipRoute
  '/_authenticated/owner/dashboard': typeof AuthenticatedOwnerDashboardRoute
  '/_authenticated/admin/resorts/$resortId': typeof AuthenticatedAdminResortsResortIdRoute
  '/_authenticated/admin/resorts/': typeof AuthenticatedAdminResortsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/faq'
    | '/forever-business'
    | '/forever-city'
    | '/forever-holidays'
    | '/how-it-works'
    | '/membership'
    | '/offers'
    | '/admin'
    | '/member'
    | '/owner'
    | '/portal'
    | '/resorts/'
    | '/admin/analytics'
    | '/admin/dashboard'
    | '/member/bookings'
    | '/member/dashboard'
    | '/member/holidays'
    | '/member/membership'
    | '/owner/dashboard'
    | '/admin/resorts/$resortId'
    | '/admin/resorts/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/faq'
    | '/forever-business'
    | '/forever-city'
    | '/forever-holidays'
    | '/how-it-works'
    | '/membership'
    | '/offers'
    | '/admin'
    | '/member'
    | '/owner'
    | '/portal'
    | '/resorts'
    | '/admin/analytics'
    | '/admin/dashboard'
    | '/member/bookings'
    | '/member/dashboard'
    | '/member/holidays'
    | '/member/membership'
    | '/owner/dashboard'
    | '/admin/resorts/$resortId'
    | '/admin/resorts'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/contact'
    | '/faq'
    | '/forever-business'
    | '/forever-city'
    | '/forever-holidays'
    | '/how-it-works'
    | '/membership'
    | '/offers'
    | '/_authenticated/admin'
    | '/_authenticated/member'
    | '/_authenticated/owner'
    | '/_authenticated/portal'
    | '/resorts/'
    | '/_authenticated/admin/analytics'
    | '/_authenticated/admin/dashboard'
    | '/_authenticated/member/bookings'
    | '/_authenticated/member/dashboard'
    | '/_authenticated/member/holidays'
    | '/_authenticated/member/membership'
    | '/_authenticated/owner/dashboard'
    | '/_authenticated/admin/resorts/$resortId'
    | '/_authenticated/admin/resorts/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  ForeverBusinessRoute: typeof ForeverBusinessRoute
  ForeverCityRoute: typeof ForeverCityRoute
  ForeverHolidaysRoute: typeof ForeverHolidaysRoute
  HowItWorksRoute: typeof HowItWorksRoute
  MembershipRoute: typeof MembershipRoute
  OffersRoute: typeof OffersRoute
  ResortsIndexRoute: typeof ResortsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forever-business': {
      id: '/forever-business'
      path: '/forever-business'
      fullPath: '/forever-business'
      preLoaderRoute: typeof ForeverBusinessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forever-city': {
      id: '/forever-city'
      path: '/forever-city'
      fullPath: '/forever-city'
      preLoaderRoute: typeof ForeverCityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forever-holidays': {
      id: '/forever-holidays'
      path: '/forever-holidays'
      fullPath: '/forever-holidays'
      preLoaderRoute: typeof ForeverHolidaysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/membership': {
      id: '/membership'
      path: '/membership'
      fullPath: '/membership'
      preLoaderRoute: typeof MembershipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offers': {
      id: '/offers'
      path: '/offers'
      fullPath: '/offers'
      preLoaderRoute: typeof OffersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/member': {
      id: '/_authenticated/member'
      path: '/member'
      fullPath: '/member'
      preLoaderRoute: typeof AuthenticatedMemberRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/owner': {
      id: '/_authenticated/owner'
      path: '/owner'
      fullPath: '/owner'
      preLoaderRoute: typeof AuthenticatedOwnerRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/portal': {
      id: '/_authenticated/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof AuthenticatedPortalRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/resorts/': {
      id: '/resorts/'
      path: '/resorts'
      fullPath: '/resorts/'
      preLoaderRoute: typeof ResortsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/analytics': {
      id: '/_authenticated/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AuthenticatedAdminAnalyticsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/dashboard': {
      id: '/_authenticated/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AuthenticatedAdminDashboardRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/member/bookings': {
      id: '/_authenticated/member/bookings'
      path: '/bookings'
      fullPath: '/member/bookings'
      preLoaderRoute: typeof AuthenticatedMemberBookingsRouteImport
      parentRoute: typeof AuthenticatedMemberRouteRoute
    }
    '/_authenticated/member/dashboard': {
      id: '/_authenticated/member/dashboard'
      path: '/dashboard'
      fullPath: '/member/dashboard'
      preLoaderRoute: typeof AuthenticatedMemberDashboardRouteImport
      parentRoute: typeof AuthenticatedMemberRouteRoute
    }
    '/_authenticated/member/holidays': {
      id: '/_authenticated/member/holidays'
      path: '/holidays'
      fullPath: '/member/holidays'
      preLoaderRoute: typeof AuthenticatedMemberHolidaysRouteImport
      parentRoute: typeof AuthenticatedMemberRouteRoute
    }
    '/_authenticated/member/membership': {
      id: '/_authenticated/member/membership'
      path: '/membership'
      fullPath: '/member/membership'
      preLoaderRoute: typeof AuthenticatedMemberMembershipRouteImport
      parentRoute: typeof AuthenticatedMemberRouteRoute
    }
    '/_authenticated/owner/dashboard': {
      id: '/_authenticated/owner/dashboard'
      path: '/dashboard'
      fullPath: '/owner/dashboard'
      preLoaderRoute: typeof AuthenticatedOwnerDashboardRouteImport
      parentRoute: typeof AuthenticatedOwnerRouteRoute
    }
    '/_authenticated/admin/resorts/': {
      id: '/_authenticated/admin/resorts/'
      path: '/resorts'
      fullPath: '/admin/resorts/'
      preLoaderRoute: typeof AuthenticatedAdminResortsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/resorts/$resortId': {
      id: '/_authenticated/admin/resorts/$resortId'
      path: '/resorts/$resortId'
      fullPath: '/admin/resorts/$resortId'
      preLoaderRoute: typeof AuthenticatedAdminResortsResortIdRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminAnalyticsRoute: typeof AuthenticatedAdminAnalyticsRoute
  AuthenticatedAdminDashboardRoute: typeof AuthenticatedAdminDashboardRoute
  AuthenticatedAdminResortsResortIdRoute: typeof AuthenticatedAdminResortsResortIdRoute
  AuthenticatedAdminResortsIndexRoute: typeof AuthenticatedAdminResortsIndexRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminAnalyticsRoute: AuthenticatedAdminAnalyticsRoute,
    AuthenticatedAdminDashboardRoute: AuthenticatedAdminDashboardRoute,
    AuthenticatedAdminResortsResortIdRoute:
      AuthenticatedAdminResortsResortIdRoute,
    AuthenticatedAdminResortsIndexRoute: AuthenticatedAdminResortsIndexRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedMemberRouteRouteChildren {
  AuthenticatedMemberBookingsRoute: typeof AuthenticatedMemberBookingsRoute
  AuthenticatedMemberDashboardRoute: typeof AuthenticatedMemberDashboardRoute
  AuthenticatedMemberHolidaysRoute: typeof AuthenticatedMemberHolidaysRoute
  AuthenticatedMemberMembershipRoute: typeof AuthenticatedMemberMembershipRoute
}

const AuthenticatedMemberRouteRouteChildren: AuthenticatedMemberRouteRouteChildren =
  {
    AuthenticatedMemberBookingsRoute: AuthenticatedMemberBookingsRoute,
    AuthenticatedMemberDashboardRoute: AuthenticatedMemberDashboardRoute,
    AuthenticatedMemberHolidaysRoute: AuthenticatedMemberHolidaysRoute,
    AuthenticatedMemberMembershipRoute: AuthenticatedMemberMembershipRoute,
  }

const AuthenticatedMemberRouteRouteWithChildren =
  AuthenticatedMemberRouteRoute._addFileChildren(
    AuthenticatedMemberRouteRouteChildren,
  )

interface AuthenticatedOwnerRouteRouteChildren {
  AuthenticatedOwnerDashboardRoute: typeof AuthenticatedOwnerDashboardRoute
}

const AuthenticatedOwnerRouteRouteChildren: AuthenticatedOwnerRouteRouteChildren =
  {
    AuthenticatedOwnerDashboardRoute: AuthenticatedOwnerDashboardRoute,
  }

const AuthenticatedOwnerRouteRouteWithChildren =
  AuthenticatedOwnerRouteRoute._addFileChildren(
    AuthenticatedOwnerRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedMemberRouteRoute: typeof AuthenticatedMemberRouteRouteWithChildren
  AuthenticatedOwnerRouteRoute: typeof AuthenticatedOwnerRouteRouteWithChildren
  AuthenticatedPortalRoute: typeof AuthenticatedPortalRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedMemberRouteRoute: AuthenticatedMemberRouteRouteWithChildren,
  AuthenticatedOwnerRouteRoute: AuthenticatedOwnerRouteRouteWithChildren,
  AuthenticatedPortalRoute: AuthenticatedPortalRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  ForeverBusinessRoute: ForeverBusinessRoute,
  ForeverCityRoute: ForeverCityRoute,
  ForeverHolidaysRoute: ForeverHolidaysRoute,
  HowItWorksRoute: HowItWorksRoute,
  MembershipRoute: MembershipRoute,
  OffersRoute: OffersRoute,
  ResortsIndexRoute: ResortsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
