/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as MembershipRouteImport } from './routes/membership'
import { Route as OffersRouteImport } from './routes/offers'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as AuthenticatedMemberRouteRouteImport } from './routes/_authenticated/member/route'
import { Route as AuthenticatedOwnerRouteRouteImport } from './routes/_authenticated/owner/route'
import { Route as AuthenticatedPortalRouteImport } from './routes/_authenticated/portal'
import { Route as ResortsIndexRouteImport } from './routes/resorts.index'
import { Route as AuthenticatedAdminDashboardRouteImport } from './routes/_authenticated/admin/dashboard'
import { Route as AuthenticatedMemberDashboardRouteImport } from './routes/_authenticated/member/dashboard'
import { Route as AuthenticatedOwnerDashboardRouteImport } from './routes/_authenticated/owner/dashboard'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const MembershipRoute = MembershipRouteImport.update({
  id: '/membership',
  path: '/membership',
  getParentRoute: () => rootRouteImport,
} as any)
const OffersRoute = OffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMemberRouteRoute =
  AuthenticatedMemberRouteRouteImport.update({
    id: '/member',
    path: '/member',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOwnerRouteRoute = AuthenticatedOwnerRouteRouteImport.update({
  id: '/owner',
  path: '/owner',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPortalRoute = AuthenticatedPortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ResortsIndexRoute = ResortsIndexRouteImport.update({
  id: '/resorts/',
  path: '/resorts/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminDashboardRoute =
  AuthenticatedAdminDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedMemberDashboardRoute =
  AuthenticatedMemberDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedMemberRouteRoute,
  } as any)
const AuthenticatedOwnerDashboardRoute =
  AuthenticatedOwnerDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedOwnerRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/how-it-works': typeof HowItWorksRoute
  '/membership': typeof MembershipRoute
  '/offers': typeof OffersRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/member': typeof AuthenticatedMemberRouteRouteWithChildren
  '/owner': typeof AuthenticatedOwnerRouteRouteWithChildren
  '/portal': typeof AuthenticatedPortalRoute
  '/resorts/': typeof ResortsIndexRoute
  '/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/member/dashboard': typeof AuthenticatedMemberDashboardRoute
  '/owner/dashboard': typeof AuthenticatedOwnerDashboardRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/how-it-works': typeof HowItWorksRoute
  '/membership': typeof MembershipRoute
  '/offers': typeof OffersRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/member': typeof AuthenticatedMemberRouteRouteWithChildren
  '/owner': typeof AuthenticatedOwnerRouteRouteWithChildren
  '/portal': typeof AuthenticatedPortalRoute
  '/resorts': typeof ResortsIndexRoute
  '/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/member/dashboard': typeof AuthenticatedMemberDashboardRoute
  '/owner/dashboard': typeof AuthenticatedOwnerDashboardRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/how-it-works': typeof HowItWorksRoute
  '/membership': typeof MembershipRoute
  '/offers': typeof OffersRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/member': typeof AuthenticatedMemberRouteRouteWithChildren
  '/_authenticated/owner': typeof AuthenticatedOwnerRouteRouteWithChildren
  '/_authenticated/portal': typeof AuthenticatedPortalRoute
  '/resorts/': typeof ResortsIndexRoute
  '/_authenticated/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/_authenticated/member/dashboard': typeof AuthenticatedMemberDashboardRoute
  '/_authenticated/owner/dashboard': typeof AuthenticatedOwnerDashboardRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/faq'
    | '/how-it-works'
    | '/membership'
    | '/offers'
    | '/admin'
    | '/member'
    | '/owner'
    | '/portal'
    | '/resorts/'
    | '/admin/dashboard'
    | '/member/dashboard'
    | '/owner/dashboard'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/faq'
    | '/how-it-works'
    | '/membership'
    | '/offers'
    | '/admin'
    | '/member'
    | '/owner'
    | '/portal'
    | '/resorts'
    | '/admin/dashboard'
    | '/member/dashboard'
    | '/owner/dashboard'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/contact'
    | '/faq'
    | '/how-it-works'
    | '/membership'
    | '/offers'
    | '/_authenticated/admin'
    | '/_authenticated/member'
    | '/_authenticated/owner'
    | '/_authenticated/portal'
    | '/resorts/'
    | '/_authenticated/admin/dashboard'
    | '/_authenticated/member/dashboard'
    | '/_authenticated/owner/dashboard'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  HowItWorksRoute: typeof HowItWorksRoute
  MembershipRoute: typeof MembershipRoute
  OffersRoute: typeof OffersRoute
  ResortsIndexRoute: typeof ResortsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/membership': {
      id: '/membership'
      path: '/membership'
      fullPath: '/membership'
      preLoaderRoute: typeof MembershipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offers': {
      id: '/offers'
      path: '/offers'
      fullPath: '/offers'
      preLoaderRoute: typeof OffersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/member': {
      id: '/_authenticated/member'
      path: '/member'
      fullPath: '/member'
      preLoaderRoute: typeof AuthenticatedMemberRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/owner': {
      id: '/_authenticated/owner'
      path: '/owner'
      fullPath: '/owner'
      preLoaderRoute: typeof AuthenticatedOwnerRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/portal': {
      id: '/_authenticated/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof AuthenticatedPortalRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/resorts/': {
      id: '/resorts/'
      path: '/resorts'
      fullPath: '/resorts/'
      preLoaderRoute: typeof ResortsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/dashboard': {
      id: '/_authenticated/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AuthenticatedAdminDashboardRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/member/dashboard': {
      id: '/_authenticated/member/dashboard'
      path: '/dashboard'
      fullPath: '/member/dashboard'
      preLoaderRoute: typeof AuthenticatedMemberDashboardRouteImport
      parentRoute: typeof AuthenticatedMemberRouteRoute
    }
    '/_authenticated/owner/dashboard': {
      id: '/_authenticated/owner/dashboard'
      path: '/dashboard'
      fullPath: '/owner/dashboard'
      preLoaderRoute: typeof AuthenticatedOwnerDashboardRouteImport
      parentRoute: typeof AuthenticatedOwnerRouteRoute
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminDashboardRoute: typeof AuthenticatedAdminDashboardRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminDashboardRoute: AuthenticatedAdminDashboardRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedMemberRouteRouteChildren {
  AuthenticatedMemberDashboardRoute: typeof AuthenticatedMemberDashboardRoute
}

const AuthenticatedMemberRouteRouteChildren: AuthenticatedMemberRouteRouteChildren =
  {
    AuthenticatedMemberDashboardRoute: AuthenticatedMemberDashboardRoute,
  }

const AuthenticatedMemberRouteRouteWithChildren =
  AuthenticatedMemberRouteRoute._addFileChildren(
    AuthenticatedMemberRouteRouteChildren,
  )

interface AuthenticatedOwnerRouteRouteChildren {
  AuthenticatedOwnerDashboardRoute: typeof AuthenticatedOwnerDashboardRoute
}

const AuthenticatedOwnerRouteRouteChildren: AuthenticatedOwnerRouteRouteChildren =
  {
    AuthenticatedOwnerDashboardRoute: AuthenticatedOwnerDashboardRoute,
  }

const AuthenticatedOwnerRouteRouteWithChildren =
  AuthenticatedOwnerRouteRoute._addFileChildren(
    AuthenticatedOwnerRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedMemberRouteRoute: typeof AuthenticatedMemberRouteRouteWithChildren
  AuthenticatedOwnerRouteRoute: typeof AuthenticatedOwnerRouteRouteWithChildren
  AuthenticatedPortalRoute: typeof AuthenticatedPortalRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedMemberRouteRoute: AuthenticatedMemberRouteRouteWithChildren,
  AuthenticatedOwnerRouteRoute: AuthenticatedOwnerRouteRouteWithChildren,
  AuthenticatedPortalRoute: AuthenticatedPortalRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  HowItWorksRoute: HowItWorksRoute,
  MembershipRoute: MembershipRoute,
  OffersRoute: OffersRoute,
  ResortsIndexRoute: ResortsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
